In [1]:
import pandas as pd

In [2]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Age": [20, 25, 22, 30, 28],
    "City": ["Delhi", "Mumbai", "Delhi", "Kolkata", "Mumbai"],
    "Salary": [30000, 50000, 45000, 70000, 60000]
})

print(df)

      Name  Age     City  Salary
0    Alice   20    Delhi   30000
1      Bob   25   Mumbai   50000
2  Charlie   22    Delhi   45000
3    David   30  Kolkata   70000
4      Eva   28   Mumbai   60000

In [3]:
## selecting column(single)
df["Age"]  ## series

0    20
1    25
2    22
3    30
4    28
Name: Age, dtype: int64

In [4]:
# selecting column (multiple)
df[["Name", "Salary"]] ## dataframe

      Name  Salary
0    Alice   30000
1      Bob   50000
2  Charlie   45000
3    David   70000
4      Eva   60000

In [5]:
## selecting rows using loc and iloc

### iloc

df.iloc[0]  ## 1st row

Name      Alice
Age          20
City      Delhi
Salary    30000
Name: 0, dtype: object

In [6]:
df.iloc[1]  ## 2nd row

Name         Bob
Age           25
City      Mumbai
Salary     50000
Name: 1, dtype: object

In [7]:
df.iloc[:3] ## first 3 rows

      Name  Age    City  Salary
0    Alice   20   Delhi   30000
1      Bob   25  Mumbai   50000
2  Charlie   22   Delhi   45000

In [8]:
df.iloc[1:4]  ## 2nd to 4th row

      Name  Age     City  Salary
1      Bob   25   Mumbai   50000
2  Charlie   22    Delhi   45000
3    David   30  Kolkata   70000

In [9]:
df.iloc[[0, 2, 4]]  ## specific row

      Name  Age    City  Salary
0    Alice   20   Delhi   30000
2  Charlie   22   Delhi   45000
4      Eva   28  Mumbai   60000

In [10]:
df.iloc[0:3, 2:3]  ## [row, col]

     City
0   Delhi
1  Mumbai
2   Delhi

In [11]:
## loc = label
df.loc[0]  ## same as iloc

Name      Alice
Age          20
City      Delhi
Salary    30000
Name: 0, dtype: object

In [12]:
df.loc[1]  ## same as iloc

Name         Bob
Age           25
City      Mumbai
Salary     50000
Name: 1, dtype: object

In [13]:
df.loc[:3] ## 4th row included

      Name  Age     City  Salary
0    Alice   20    Delhi   30000
1      Bob   25   Mumbai   50000
2  Charlie   22    Delhi   45000
3    David   30  Kolkata   70000

In [14]:
df.loc[1:4] ## 2nd to 5th row

      Name  Age     City  Salary
1      Bob   25   Mumbai   50000
2  Charlie   22    Delhi   45000
3    David   30  Kolkata   70000
4      Eva   28   Mumbai   60000

In [15]:
df.loc[[0, 2, 4]]  ## same as iloc

      Name  Age    City  Salary
0    Alice   20   Delhi   30000
2  Charlie   22   Delhi   45000
4      Eva   28  Mumbai   60000

In [16]:
## df.loc[row, column] wont work unless column names are specified

In [17]:
## filtering rows
df[df["Salary"]>50000]

    Name  Age     City  Salary
3  David   30  Kolkata   70000
4    Eva   28   Mumbai   60000

In [18]:
df[df["City"] == "Delhi"]

      Name  Age   City  Salary
0    Alice   20  Delhi   30000
2  Charlie   22  Delhi   45000

In [19]:
## multiple condition (and = & and or = |)
df[(df["Salary"]>50000) & (df["City"] == "Mumbai")]

  Name  Age    City  Salary
4  Eva   28  Mumbai   60000

In [20]:
df[(df["City"] == "Delhi") | (df["City"] == "Mumbai")]

      Name  Age    City  Salary
0    Alice   20   Delhi   30000
1      Bob   25  Mumbai   50000
2  Charlie   22   Delhi   45000
4      Eva   28  Mumbai   60000

In [21]:
## isin()  ## clean, simple and fast for big datasets
df[df["City"].isin(["Delhi", "Mumbai"])]

      Name  Age    City  Salary
0    Alice   20   Delhi   30000
1      Bob   25  Mumbai   50000
2  Charlie   22   Delhi   45000
4      Eva   28  Mumbai   60000

In [22]:
## between
df[df["Age"].between(20,25)]

      Name  Age    City  Salary
0    Alice   20   Delhi   30000
1      Bob   25  Mumbai   50000
2  Charlie   22   Delhi   45000

In [23]:
## query()
df.query("Age<=25 and Age>=20")

      Name  Age    City  Salary
0    Alice   20   Delhi   30000
1      Bob   25  Mumbai   50000
2  Charlie   22   Delhi   45000

In [24]:
## sorting  ## default ascending
df.sort_values(["Salary"])

      Name  Age     City  Salary
0    Alice   20    Delhi   30000
2  Charlie   22    Delhi   45000
1      Bob   25   Mumbai   50000
4      Eva   28   Mumbai   60000
3    David   30  Kolkata   70000

In [25]:
## descencding
df.sort_values(["Salary"], ascending=False)

      Name  Age     City  Salary
3    David   30  Kolkata   70000
4      Eva   28   Mumbai   60000
1      Bob   25   Mumbai   50000
2  Charlie   22    Delhi   45000
0    Alice   20    Delhi   30000

In [26]:
## sort by 2 columns
df.sort_values(["City", "Age"])

      Name  Age     City  Salary
0    Alice   20    Delhi   30000
2  Charlie   22    Delhi   45000
3    David   30  Kolkata   70000
1      Bob   25   Mumbai   50000
4      Eva   28   Mumbai   60000

In [27]:
## rename column name
df.rename(columns={"Salary": "Monthly_salary"})

      Name  Age     City  Monthly_salary
0    Alice   20    Delhi           30000
1      Bob   25   Mumbai           50000
2  Charlie   22    Delhi           45000
3    David   30  Kolkata           70000
4      Eva   28   Mumbai           60000

In [28]:
df

      Name  Age     City  Salary
0    Alice   20    Delhi   30000
1      Bob   25   Mumbai   50000
2  Charlie   22    Delhi   45000
3    David   30  Kolkata   70000
4      Eva   28   Mumbai   60000

In [29]:
df.rename(columns={"Salary": "Monthly_salary"}, inplace=True)

In [30]:
df

      Name  Age     City  Monthly_salary
0    Alice   20    Delhi           30000
1      Bob   25   Mumbai           50000
2  Charlie   22    Delhi           45000
3    David   30  Kolkata           70000
4      Eva   28   Mumbai           60000