In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "Alice", None],
    "Age": [20, 25, np.nan, 20, 28],
    "City": ["Delhi", "Mumbai", "Delhi", " ", " Kolkata "],
    "Salary": [30000, None, 45000, 30000, 60000]
})

print(df)

      Name   Age       City   Salary
0    Alice  20.0      Delhi  30000.0
1      Bob  25.0     Mumbai      NaN
2  Charlie   NaN      Delhi  45000.0
3    Alice  20.0             30000.0
4      NaN  28.0   Kolkata   60000.0

In [4]:
## missing value
df.isnull().sum()

Name      1
Age       1
City      0
Salary    1
dtype: int64

In [5]:
## drop missing value
df.dropna()

    Name   Age   City   Salary
0  Alice  20.0  Delhi  30000.0
3  Alice  20.0         30000.0

In [24]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "Alice", None],
    "Age": [20, 25, np.nan, np.nan, 28],
    "City": ["Delhi", "Mumbai", "Delhi", " ", " Kolkata "],
    "Salary": [30000, None, 45000, 30000, 60000]
})

print(df)

      Name   Age       City   Salary
0    Alice  20.0      Delhi  30000.0
1      Bob  25.0     Mumbai      NaN
2  Charlie   NaN      Delhi  45000.0
3    Alice   NaN             30000.0
4      NaN  28.0   Kolkata   60000.0

In [25]:
## fill with random value

df["Age"] = df["Age"].fillna(30)
df

      Name   Age       City   Salary
0    Alice  20.0      Delhi  30000.0
1      Bob  25.0     Mumbai      NaN
2  Charlie  30.0      Delhi  45000.0
3    Alice  30.0             30000.0
4      NaN  28.0   Kolkata   60000.0

In [26]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "Alice", None],
    "Age": [20, 25, np.nan, np.nan, 28],
    "City": ["Delhi", "Mumbai", "Delhi", " ", " Kolkata "],
    "Salary": [30000, None, 45000, 30000, 60000]
})

print(df)

      Name   Age       City   Salary
0    Alice  20.0      Delhi  30000.0
1      Bob  25.0     Mumbai      NaN
2  Charlie   NaN      Delhi  45000.0
3    Alice   NaN             30000.0
4      NaN  28.0   Kolkata   60000.0

In [ ]:
## fill with mean value
df["Age"] = df["Age"].fillna(df["Age"].mean()) 
df

      Name        Age       City   Salary
0    Alice  20.000000      Delhi  30000.0
1      Bob  25.000000     Mumbai      NaN
2  Charlie  24.333333      Delhi  45000.0
3    Alice  24.333333             30000.0
4      NaN  28.000000   Kolkata   60000.0

In [34]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "Alice", None],
    "Age": [20, 25, np.nan, 20, 28],
    "City": ["Delhi", "Mumbai", "Delhi", "Delhi", " Kolkata "],
    "Salary": [30000, None, 45000, 30000, 60000]
})

print(df)
## Detect Duplicate Rows
df.duplicated()

      Name   Age       City   Salary
0    Alice  20.0      Delhi  30000.0
1      Bob  25.0     Mumbai      NaN
2  Charlie   NaN      Delhi  45000.0
3    Alice  20.0      Delhi  30000.0
4      NaN  28.0   Kolkata   60000.0

0    False
1    False
2    False
3     True
4    False
dtype: bool

In [35]:
## drop duplicates
df = df.drop_duplicates()
df

      Name   Age       City   Salary
0    Alice  20.0      Delhi  30000.0
1      Bob  25.0     Mumbai      NaN
2  Charlie   NaN      Delhi  45000.0
4      NaN  28.0   Kolkata   60000.0

In [40]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "Alice", None],
    "Age": [20, 25, np.nan, 20, 28],
    "City": ["Delhi", "Mumbai", "Delhi", "    Delhi", " Kolkata     "],
    "Salary": [30000, None, 45000, 30000, 60000]
})
print(df)
# Remove Extra Spaces
df["City"].str.strip()
df

      Name   Age           City   Salary
0    Alice  20.0          Delhi  30000.0
1      Bob  25.0         Mumbai      NaN
2  Charlie   NaN          Delhi  45000.0
3    Alice  20.0          Delhi  30000.0
4      NaN  28.0   Kolkata       60000.0

      Name   Age           City   Salary
0    Alice  20.0          Delhi  30000.0
1      Bob  25.0         Mumbai      NaN
2  Charlie   NaN          Delhi  45000.0
3    Alice  20.0          Delhi  30000.0
4      NaN  28.0   Kolkata       60000.0

In [42]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "Alice", None],
    "Age": [20, 25, np.nan, 20, 28],
    "City": ["DelhI", "MUMbai", "DeLhi", "    Delhi", " KOlKata     "],
    "Salary": [30000, None, 45000, 30000, 60000]
})
## Change text case
df["City"].str.upper().str.strip()

0      DELHI
1     MUMBAI
2      DELHI
3      DELHI
4    KOLKATA
Name: City, dtype: str

In [45]:
## for lower case 
df["City"].str.lower().str.strip()

0      delhi
1     mumbai
2      delhi
3      delhi
4    kolkata
Name: City, dtype: str

In [47]:
df["City"].str.title()

0            Delhi
1           Mumbai
2            Delhi
3            Delhi
4     Kolkata
Name: City, dtype: str

In [59]:
## replace values
df["City"] = df["City"].str.title().str.strip()
print(df)
df["City"] = df["City"].replace("Delhi","NewDelhi")
df

      Name   Age     City   Salary
0    Alice  20.0    Delhi  30000.0
1      Bob  25.0   Mumbai      NaN
2  Charlie   NaN    Delhi  45000.0
3    Alice  20.0    Delhi  30000.0
4      NaN  28.0  Kolkata  60000.0

      Name   Age      City   Salary
0    Alice  20.0  NewDelhi  30000.0
1      Bob  25.0    Mumbai      NaN
2  Charlie   NaN  NewDelhi  45000.0
3    Alice  20.0  NewDelhi  30000.0
4      NaN  28.0   Kolkata  60000.0

In [60]:
## Data Type Conversion
df.dtypes

Name          str
Age       float64
City          str
Salary    float64
dtype: object

In [62]:
df["Salary"] = df["Salary"].astype("f16")
df

      Name   Age      City   Salary
0    Alice  20.0  NewDelhi  30000.0
1      Bob  25.0    Mumbai      NaN
2  Charlie   NaN  NewDelhi  45000.0
3    Alice  20.0  NewDelhi  30000.0
4      NaN  28.0   Kolkata  60000.0

In [64]:
df["Age"] = pd.to_numeric(
    df["Age"],
    errors="coerce"
)
df

      Name   Age      City   Salary
0    Alice  20.0  NewDelhi  30000.0
1      Bob  25.0    Mumbai      NaN
2  Charlie   NaN  NewDelhi  45000.0
3    Alice  20.0  NewDelhi  30000.0
4      NaN  28.0   Kolkata  60000.0

In [65]:
## Unique values
df["City"].unique()

<StringArray>
['NewDelhi', 'Mumbai', 'Kolkata']
Length: 3, dtype: str

In [ ]:
df["City"].nunique()  ## count unique

3

In [69]:
## Value Counts
df["City"].value_counts()

City
NewDelhi    3
Mumbai      1
Kolkata     1
Name: count, dtype: int64

In [75]:
## Rename column
df.rename(columns = {"City":"Town"}, inplace=True)
df

      Name   Age      Town   Salary
0    Alice  20.0  NewDelhi  30000.0
1      Bob  25.0    Mumbai      NaN
2  Charlie   NaN  NewDelhi  45000.0
3    Alice  20.0  NewDelhi  30000.0
4      NaN  28.0   Kolkata  60000.0

In [76]:
## Create new column
df["YearlySalary"] = df["Salary"]*12

In [77]:
df

      Name   Age      Town   Salary  YearlySalary
0    Alice  20.0  NewDelhi  30000.0      360000.0
1      Bob  25.0    Mumbai      NaN           NaN
2  Charlie   NaN  NewDelhi  45000.0      540000.0
3    Alice  20.0  NewDelhi  30000.0      360000.0
4      NaN  28.0   Kolkata  60000.0      720000.0