In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Employee": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank"],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "IT"],
    "City": ["Delhi", "Mumbai", "Delhi", "Kolkata", "Mumbai", "Delhi"],
    "Salary": [50000, 40000, 60000, 70000, 45000, 55000],
    "Experience": [2, 5, 3, 7, 4, 6]
})

print(df)

  Employee Department     City  Salary  Experience
0    Alice         IT    Delhi   50000           2
1      Bob         HR   Mumbai   40000           5
2  Charlie         IT    Delhi   60000           3
3    David    Finance  Kolkata   70000           7
4      Eva         HR   Mumbai   45000           4
5    Frank         IT    Delhi   55000           6

In [ ]:
## groupby
df.groupby("City")["Salary"].mean()

City
Delhi      55000.0
Kolkata    70000.0
Mumbai     42500.0
Name: Salary, dtype: float64

In [9]:
## count
df.groupby("Department").size()

Department
Finance    1
HR         2
IT         3
dtype: int64

In [ ]:
df.groupby("Department")["Employee"].count()  ## count ignores NaN

Department
Finance    1
HR         2
IT         3
Name: Employee, dtype: int64

In [14]:
## sum
df.groupby("Department")["Salary"].sum()

Department
Finance     70000
HR          85000
IT         165000
Name: Salary, dtype: int64

In [15]:
## maximum
df.groupby("Department")["Salary"].max()

Department
Finance    70000
HR         45000
IT         60000
Name: Salary, dtype: int64

In [16]:
## minimum
df.groupby("Department")["Salary"].min()

Department
Finance    70000
HR         40000
IT         50000
Name: Salary, dtype: int64

In [18]:
## aggregation
df.groupby("Department")["Salary"].agg(["min","max","mean","median","sum","count"])

              min    max     mean   median     sum  count
Department
Finance     70000  70000  70000.0  70000.0   70000      1
HR          40000  45000  42500.0  42500.0   85000      2
IT          50000  60000  55000.0  55000.0  165000      3

In [23]:
## multiple column
df.groupby(
    ["Department", "City"]
)["Salary"].mean()

Department  City
Finance     Kolkata    70000.0
HR          Mumbai     42500.0
IT          Delhi      55000.0
Name: Salary, dtype: float64

In [2]:
## named aggregation
df.groupby("Department").agg(
    averagesalary = ("Salary", "mean"),
    maxsalary = ("Salary", "max"),
    minsalary = ("Salary", "min")
)

            averagesalary  maxsalary  minsalary
Department
Finance           70000.0      70000      70000
HR                42500.0      45000      40000
IT                55000.0      60000      50000

In [22]:
## groupby multiple metric
data = df.groupby("Department").agg({
    "Salary" : ["mean", "max", "min"],
    "Experience" : ["mean", "max"]
})

In [24]:
df.columns = [
    "".join(col)
    for col in data.columns
]
df

  Salarymean Salarymax Salarymin  Experiencemean  Experiencemax
0      Alice        IT     Delhi           50000              2
1        Bob        HR    Mumbai           40000              5
2    Charlie        IT     Delhi           60000              3
3      David   Finance   Kolkata           70000              7
4        Eva        HR    Mumbai           45000              4
5      Frank        IT     Delhi           55000              6

In [28]:
## Transform
df["DeptAvgSalary"] = (
    df.groupby("Department")["Salary"]
      .transform("mean")
)
df

  Employee Department     City  Salary  Experience  DeptAvgSalary
0    Alice         IT    Delhi   50000           2        55000.0
1      Bob         HR   Mumbai   40000           5        42500.0
2  Charlie         IT    Delhi   60000           3        55000.0
3    David    Finance  Kolkata   70000           7        70000.0
4      Eva         HR   Mumbai   45000           4        42500.0
5    Frank         IT    Delhi   55000           6        55000.0

In [29]:
df.groupby("Department").filter(
    lambda x: len(x) > 2
)

  Employee Department   City  Salary  Experience  DeptAvgSalary
0    Alice         IT  Delhi   50000           2        55000.0
2  Charlie         IT  Delhi   60000           3        55000.0
5    Frank         IT  Delhi   55000           6        55000.0

In [30]:
pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    aggfunc="mean"
)

             Salary
Department
Finance     70000.0
HR          42500.0
IT          55000.0